USE alph;
SET SQL_SAFE_UPDATES = 0;

DELETE FROM PRIVATEIP;
DELETE FROM TERMINAL_GROUP;
DELETE FROM TERMINAL_DIRECTORY;
DELETE FROM TERMINAL_FILE;
DELETE FROM TERMINAL_GROUP_LINK;
DELETE FROM TERMINAL_USER;
DELETE FROM TERMINAL;
DELETE FROM NETWORK;
DELETE FROM ACCOUNT_VALIDATION;
DELETE FROM ACCOUNT;

-- DELETE FROM SESSION;
-- DELETE FROM CONFIG;