USE alph;

ALTER TABLE `TERMINAL_DIRECTORY` DROP FOREIGN KEY `TERMINAL_DIRECTORY_fk0`;

ALTER TABLE `TERMINAL_DIRECTORY` DROP FOREIGN KEY `TERMINAL_DIRECTORY_fk1`;

ALTER TABLE `TERMINAL_FILE` DROP FOREIGN KEY `TERMINAL_FILE_fk0`;

ALTER TABLE `TERMINAL_FILE` DROP FOREIGN KEY `TERMINAL_FILE_fk1`;

ALTER TABLE `TERMINAL` DROP FOREIGN KEY `TERMINAL_fk0`;

ALTER TABLE `TERMINAL` DROP FOREIGN KEY `TERMINAL_fk1`;

ALTER TABLE `PORT` DROP FOREIGN KEY `PORT_fk0`;

ALTER TABLE `PRIVATEIP` DROP FOREIGN KEY `PRIVATEIP_fk0`;

ALTER TABLE `PRIVATEIP` DROP FOREIGN KEY `PRIVATEIP_fk1`;

ALTER TABLE `TERMINAL_USER` DROP FOREIGN KEY `TERMINAL_USER_fk0`;

ALTER TABLE `TERMINAL_GROUP` DROP FOREIGN KEY `TERMINAL_GROUP_fk0`;

ALTER TABLE `TERMINAL_GROUP_LINK` DROP FOREIGN KEY `TERMINAL_GROUP_LINK_fk0`;

ALTER TABLE `TERMINAL_GROUP_LINK` DROP FOREIGN KEY `TERMINAL_GROUP_LINK_fk1`;

ALTER TABLE `TERMINAL_USER_HISTORY` DROP FOREIGN KEY `TERMINAL_USER_HISTORY_fk0`;

ALTER TABLE `ACCOUNT_VALIDATION` DROP FOREIGN KEY `ACCOUNT_VALIDATION_fk0`;

DROP TABLE IF EXISTS `ACCOUNT`;

DROP TABLE IF EXISTS `TERMINAL_DIRECTORY`;

DROP TABLE IF EXISTS `TERMINAL_FILE`;

DROP TABLE IF EXISTS `TERMINAL`;

DROP TABLE IF EXISTS `NETWORK`;

DROP TABLE IF EXISTS `PORT`;

DROP TABLE IF EXISTS `PRIVATEIP`;

DROP TABLE IF EXISTS `TERMINAL_USER`;

DROP TABLE IF EXISTS `TERMINAL_GROUP`;

DROP TABLE IF EXISTS `TERMINAL_GROUP_LINK`;

DROP TABLE IF EXISTS `SESSION`;

DROP TABLE IF EXISTS `TERMINAL_USER_HISTORY`;

DROP TABLE IF EXISTS `ACCOUNT_VALIDATION`;

DROP TABLE IF EXISTS `CONFIG`;
